# Generated by Django 4.2.6 on 2023-10-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('documento', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45, null=True)),
                ('telefono', models.CharField(max_length=45, null=True)),
                ('ciudad', models.CharField(max_length=45, null=True)),
                ('tipo_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.tipopersona')),
            ],
        ),
    ]
