# Generated by Django 4.2.6 on 2023-10-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multas', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicarMultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multas.multa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.personas')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculos')),
            ],
        ),
    ]
